### ISSUE TITLE
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict

### ISSUE THREAD

**Issue by sam-s** [jpmml/jpmml-sklearn#111] opened 2019-07-31 16:40 UTC
```
>>> sklearn.__version__
'0.21.2'
>>> sklearn2pmml.__version__
'0.48.0'
```

In the same code as https://github.com/jpmml/sklearn2pmml/issues/154, I now get this:

```
Standard output is empty
Standard error:
Jul 31, 2019 12:33:15 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 31, 2019 12:33:15 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.random._pickle.__randomstate_ctor)
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:773)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:213)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:123)
	at numpy.core.NDArrayUtil.readObject(NDArrayUtil.java:378)
	at numpy.core.TypeDescriptor.read(TypeDescriptor.java:163)
	at numpy.core.NDArrayUtil.parseArray(NDArrayUtil.java:214)
	at numpy.core.NDArrayUtil.parseData(NDArrayUtil.java:189)
	at joblib.NumpyArrayWrapper.toArray(NumpyArrayWrapper.java:43)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:88)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:123)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```

**Comment by vruusmann** [comment] 2019-07-31 19:32
The pickle file contains a reference to Numpy's ranomd object (a CPython class, which uses a custom constructor). How did it get there? Are you passing it as `random_state` attribute?

To work around this problem, use `random_state = <int>`.

**Comment by sam-s** [comment] 2019-07-31 19:43
I do not manipulate random states myself.

**Comment by vruusmann** [comment] 2019-07-31 19:48
> I do not manipulate random states myself.

Still, what do you think - where is this Numpy random object coming into your pickle file? For starters, what's the model type?

There is a mapping for Numpy random:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties#L18

However, the existing mapping is for `numpy.random.__RandomState_ctor` whereas your runtime uses `numpy.random._pickle.__randomstate_ctor`.

**Comment by sam-s** [comment] 2019-07-31 21:06
model is `GradientBoostingClassifier`.

**Comment by sam-s** [comment] 2019-08-20 18:44
```python
from sklearn2pmml import sklearn2pmml, PMMLPipeline
from sklearn import datasets
from sklearn.ensemble import GradientBoostingClassifier

iris = datasets.load_iris()
gbc = GradientBoostingClassifier()
iris_pipeline = PMMLPipeline([("classifier", gbc)])
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_pipeline.fit(iris_df, pd.Series(iris.target, name="species"))
sklearn2pmml(iris_pipeline, "iris.pmml", with_repr=True)
```

**Comment by vruusmann** [comment] 2019-08-30 06:26
Closing as fake/non-reproducible issue.

The above code (https://github.com/jpmml/jpmml-sklearn/issues/111#issuecomment-523145571) runs perfectly on my Linux computer, using both Scikit-Learn 0.21.2 and 0.21.3.

**Closed by vruusmann** 2019-08-30 06:26 UTC

**Comment by vruusmann** [comment] 2019-08-30 08:21
> The above code runs perfectly on my Linux computer,

FYI, my environment:
```
python: 3.7.2
sklearn: 0.21.3
sklearn2pmml: 0.48.0
joblib: 0.13.2
sklearn_pandas: 1.8.0
pandas: 0.23.4
numpy: 1.16.0
openjdk: 1.8.0_111
```

**Comment by sam-s** [comment] 2019-08-30 20:34
> fake
what exactly are you saying?

my setup is slightly different:
```
Python 3.6.8
pandas: 0.25.0
numpy: 1.17.0
openjdk 11.0.4 2019-07-16
```
the rest have the same version

**Comment by sam-s** [comment] 2019-08-30 20:35
> > The above code runs perfectly on my Linux computer,
> 
> FYI, my environment:
> 
> ```
> python: 3.7.2
> sklearn: 0.21.3
> sklearn2pmml: 0.48.0
> joblib: 0.13.2
> sklearn_pandas: 1.8.0
> pandas: 0.23.4
> numpy: 1.16.0
> openjdk: 1.8.0_111
> ```

my setup is slightly different:
```
Python 3.6.8
pandas: 0.25.0
numpy: 1.17.0
openjdk 11.0.4 2019-07-16
```
the rest have the same version

**Comment by sam-s** [comment] 2019-08-30 20:36
> Closing as fake/non-reproducible issue.

what exactly are you saying here?

**Comment by vruusmann** [comment] 2019-08-30 21:27
> what exactly are you saying here?

The stated issue does not exist. At least I'm not able to reproduce it.

**Comment by sam-s** [comment] 2019-08-30 21:56
> > what exactly are you saying here?
> 
> The stated issue does not exist. At least I'm not able to reproduce it.

The word "fake" has a very specific meaning.
Are you accusing me of lying?

**Comment by vruusmann** [comment] 2019-08-30 22:08
> The word "fake" has a very specific meaning.

English is not my primary language. So, perhaps you can point me to an authoritative reference (eg. your favourite dictionary) that clearly lays out the true meaning of "fake".

> Are you accusing me of lying?

I don't owe you isht. Feel free to fork off.
