### ISSUE TITLE
Support for QuantileTransformer

### ISSUE THREAD

**Issue by GasCan666** [jpmml/jpmml-sklearn#191] opened 2023-12-26 10:01 UTC
Need QuantileTransformer support
In python, it's `from sklearn.preprocessing import QuantileTransformer`
This QuantileTransformer is a very import Module in data preprocessing, to improve the performance of any model

**Comment by vruusmann** [comment] 2023-12-27 07:18
Noted.

But I'd like to see five likes/upvotes on this issue first (as a proof that it's worth solving any time soon).

**Comment by vruusmann** [comment] 2024-01-01 07:48
Closing as exact duplicate of https://github.com/jpmml/jpmml-sklearn/issues/70

**Closed by vruusmann** 2024-01-01 07:48 UTC
