### ISSUE TITLE
Why is datatype continuous and double when the data is a string?

### ISSUE THREAD

**Issue by wuangKKK** [jpmml/jpmml-sklearn#123] opened 2019-11-26 07:01 UTC
<DataField name="company_city" optype="continuous" dataType="double">
			<Value value="三门峡市"/>
			<Value value="上海市"/>
			<Value value="东莞市"/>
			<Value value="东营市"/>
			<Value value="中山市"/>
			<Value value="临沂市"/>
			<Value value="丽水市"/>
			<Value value="乌鲁木齐市"/>
			<Value value="九江市"/>
			<Value value="佛山市"/>
.......

Why is datatype continuous and double when the data is a string?

**Comment by wuangKKK** [comment] 2019-11-26 07:01
<DataField name="company_city" optype="continuous" dataType="double">
			<Value value="三门峡市"/>
			<Value value="上海市"/>
			<Value value="东莞市"/>
			<Value value="东营市"/>
			<Value value="中山市"/>
			<Value value="临沂市"/>
			<Value value="丽水市"/>
			<Value value="乌鲁木齐市"/>
			<Value value="九江市"/>
			<Value value="佛山市"/>

**Comment by wuangKKK** [comment] 2019-11-26 07:02
<DataField name="company_city" optype="continuous" dataType="double">
			<Value value="aaa"/>
                         <Value value="bbb"/>
                         <Value value="ccc"/>

**Comment by vruusmann** [comment] 2019-11-26 07:11
Example?

**Comment by wuangKKK** [comment] 2019-11-26 07:13
![image](https://user-images.githubusercontent.com/25049492/69607015-4859be80-105f-11ea-97a3-2bbb9fb9cde4.png)

**Comment by wuangKKK** [comment] 2019-11-26 07:15
I saved the model like this
![image](https://user-images.githubusercontent.com/25049492/69607100-7b03b700-105f-11ea-8a0a-a8972a4cdc9a.png)

**Comment by wuangKKK** [comment] 2019-11-26 07:17
@vruusmann

**Comment by wuangKKK** [comment] 2019-11-26 07:20
pmml like this
![image](https://user-images.githubusercontent.com/25049492/69607414-26ad0700-1060-11ea-9889-4b9385d2de65.png)
@vruusmann

**Comment by vruusmann** [comment] 2019-11-26 13:40
See the source code of the DictVectorizer converter: https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/feature_extraction/DictVectorizer.java

Your feature is considered to be a numeric, because the `DictVectorizer.separator` is not specified.

**Comment by vruusmann** [comment] 2019-11-26 14:08
Looking at the source code of DictVectorizer converter again, then the field type is determined differently for new (this issue) and existing fields (my intergration tests). This needs to be unified.

**Comment by vruusmann** [comment] 2019-11-26 16:20
My code:
```python
from sklearn.feature_extraction import DictVectorizer
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline
from xgboost import XGBClassifier

import pandas

df = pandas.read_csv("Audit.csv")

df_X = df[df.columns.values[0:-1]]
df_X = df_X.to_dict("records")

df_y = df["Adjusted"]

pipeline = PMMLPipeline([
	("mapper", DictVectorizer()),
	("classifier", XGBClassifier())
])
pipeline.fit(df_X, df_y)

sklearn2pmml(pipeline, "Audit.pmml")
```

All continuous and categorical features are correctly detected as `continuous+double` and `categorical+string`, respectively.

Closing as "not reproducible". Whatever the problem, it must be related to your own application code, not the JPMML-SkLearn/SkLearn2PMML stack.

**Closed by vruusmann** 2019-11-26 16:20 UTC
