### ISSUE TITLE
How to add additional logic to PMML file after building the model?

### ISSUE THREAD

**Issue by chris7z** [jpmml/jpmml-sklearn#102] opened 2019-04-12 15:16 UTC
Hello, I'm following the Audit.csv example to create a PMML file using Audit.csv. Now that I've got the PMML file, and it contains score for each node. A snippet is like below. Now I'd like to add additional logic to say that if score is <=0.5 then 'low', if score is >0.5 then 'high'. Is it possible to add this logic inside the PMML file through the pipeline in Python? Could you provide a code example? Thanks!

								<Node id="1">
									<True/>
									<Node id="2">
										<SimplePredicate field="Occupation" operator="notEqual" value="Executive"/>
										<Node id="3">
											<SimplePredicate field="Occupation" operator="notEqual" value="Professional"/>
											<Node id="4" score="-0.45040975411720585">
												<SimplePredicate field="Education" operator="notEqual" value="Bachelor"/>
											</Node>
											<Node id="5" score="0.4834200201761715">
												<SimplePredicate field="Education" operator="equal" value="Bachelor"/>
											</Node>
										</Node>
										<Node id="6">
											<SimplePredicate field="Occupation" operator="equal" value="Professional"/>
											<Node id="7" score="0.5173738670472605">
												<SimplePredicate field="Education" operator="notEqual" value="Professional"/>
											</Node>
											<Node id="8" score="2.055645282801034">
												<SimplePredicate field="Education" operator="equal" value="Professional"/>
											</Node>
										</Node>
									</Node>

> XGBoost demo using the [Audit](https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/csv/Audit.csv) dataset:
> 
> ```python
> import pandas
> 
> df = pandas.read_csv("Audit.csv")
> 
> df["Deductions"] = df["Deductions"].replace(True, "TRUE").replace(False, "FALSE").astype(str)
> df["Adjusted"] = df["Adjusted"].astype(int)
> 
> from sklearn2pmml import sklearn2pmml, PMMLPipeline
> from sklearn2pmml.decoration import CategoricalDomain
> from sklearn.preprocessing import LabelBinarizer
> from sklearn_pandas import DataFrameMapper
> from xgboost.sklearn import XGBClassifier
> 
> mapper = DataFrameMapper([
> 	("Occupation", [CategoricalDomain(invalid_value_treatment = "as_is"), LabelBinarizer()]),
> 	("Education", [CategoricalDomain(invalid_value_treatment = "as_is"), LabelBinarizer()])
> ])
> classifier = XGBClassifier()
> 
> pipeline = PMMLPipeline([
> 	("mapper", mapper),
> 	("classifier", classifier)
> ])
> pipeline.fit(df, df["Adjusted"])
> 
> sklearn2pmml(pipeline, "pipeline.pmml", with_repr = True)
> ```
> 
> If the resulting `pipeline.pmml` file is opened in text editor, then the following `/PMML/MiningModel/MiningSchema` declaration can be seen:
> 
> ```
> <MiningSchema>
> 	<MiningField name="Adjusted" usageType="target"/>
> 	<MiningField name="Education" missingValueTreatment="asIs" invalidValueTreatment="asIs"/>
> 	<MiningField name="Occupation" missingValueTreatment="asIs" invalidValueTreatment="asIs"/>
> </MiningSchema>
> ```

**Comment by vruusmann** [comment] 2019-04-12 18:19
Closing as functional duplicate of https://github.com/jpmml/sklearn2pmml/issues/149

**Closed by vruusmann** 2019-04-12 18:19 UTC
