### ISSUE TITLE
Build problem (tests failing in razorvine lib)

### ISSUE THREAD

**Issue by bindernet** [jpmml/jpmml-sklearn#136] opened 2020-05-27 08:50 UTC
I have tests failing when trying to build the latest code.
Errors: 142

Starts like this, and they all look similar:
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 1.495 s <<< FAILURE! - in org.jpmml.sklearn.BaseEstimatorTest
[ERROR] evaluateGradientBoostingAuto(org.jpmml.sklearn.BaseEstimatorTest)  Time elapsed: 0.749 s  <<< ERROR!
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)
        at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
        at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)
        at org.jpmml.sklearn.EstimatorTest$1.getPMML(EstimatorTest.java:99)
        at org.jpmml.evaluator.testing.ArchiveBatch.getEvaluatorBuilder(ArchiveBatch.java:65)
        at org.jpmml.evaluator.testing.IntegrationTestBatch.getEvaluatorBuilder(IntegrationTestBatch.java:67)
        at org.jpmml.sklearn.EstimatorTest$1.getEvaluatorBuilder(EstimatorTest.java:82)
        at org.jpmml.evaluator.testing.ArchiveBatch.getEvaluator(ArchiveBatch.java:79)
        at org.jpmml.evaluator.testing.IntegrationTestBatch.getEvaluator(IntegrationTestBatch.java:84)
        at org.jpmml.evaluator.testing.BatchUtil.evaluate(BatchUtil.java:49)
        at org.jpmml.evaluator.testing.BatchTest.evaluate(BatchTest.java:29)
        at org.jpmml.evaluator.testing.IntegrationTest.evaluate(IntegrationTest.java:64)
        at org.jpmml.evaluator.testing.IntegrationTest.evaluate(IntegrationTest.java:42)
        at org.jpmml.sklearn.BaseEstimatorTest.evaluateGradientBoostingAuto(BaseEstimatorTest.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

I see it is similar to: 
 https://github.com/jpmml/jpmml-sklearn/issues/111  which wasn't reproducible. :-(

Things I've tried:

- I can (still) build v1.5
- Completely deleting my local maven repository

Linux
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

python: 3.8.2
numpy: 1.17.3

I can try and step through the Java code, but I would need to set up a Java dev environment first...
Any ideas?

**Comment by vruusmann** [comment] 2020-05-27 09:05
Closing as exact duplicate of https://github.com/jpmml/jpmml-python/issues/3

I don't get it - the build should be totally independent of Python package versions (SkLearn2PMML, Scikit-Learn, Pandas, Numpy). It builds fin on my computer, but not elsewhere.

**Comment by vruusmann** [comment] 2020-05-27 09:06
If the build was broken, then I couldn't make a release with Apache Maven. But I can, SMH.

**Closed by vruusmann** 2020-05-27 09:05 UTC
