### ISSUE TITLE
Unable to install this package using anaconda

### ISSUE THREAD

**Issue by ginahanspal** [jpmml/jpmml-sklearn#110] opened 2019-07-19 22:53 UTC
I am unable to install sklearn2pmml into my Anaconda environment. Any tips on how I can make this work in Jupyter notebooks? Thanks a lot!!

**Comment by vruusmann** [comment] 2019-07-20 05:37
Closing as duplicate of https://github.com/jpmml/sklearn2pmml/issues/169

**Closed by vruusmann** 2019-07-20 05:37 UTC
